name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allow this workflow to be triggered manually (ex: in GitHub UI)
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      # Checks out the repository and enables the use of commands made available in the project ie npm run
      - name: Checkout Git repository
        uses: actions/checkout@v3

      # Configure npm
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
